# Generated by Django 4.2.4 on 2024-09-06 17:47

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetMeta',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('public', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('tissue', models.CharField(max_length=100)),
                ('cells', models.IntegerField()),
                ('categories', models.JSONField(default=list)),
                ('description', models.TextField(max_length=5000)),
                ('file', models.CharField(max_length=100)),
                ('image', models.FileField(
                    storage=django.core.files.storage.FileSystemStorage(base_url='/singlocell-api/media/datasets',
                                                                        location='data/media\\datasets'),
                    upload_to='')),
                ('linksPublications', models.JSONField(blank=True, default=list, null=True)),
                ('linksDatasets', models.JSONField(blank=True, default=list, null=True)),
                ('keywords', models.JSONField(blank=True, default=list, null=True)),
                ('info', models.JSONField(default=dict)),
                ('infoDefault', models.JSONField(blank=True, default=dict, null=True)),
                ('labelsRemap', models.JSONField(blank=True, default=dict, null=True)),
                ('embeddings', models.JSONField(blank=True, default=list, null=True)),
                ('groups', models.JSONField(default=list)),
                ('pseudotime', models.JSONField(blank=True, default=list, null=True)),
                ('maintainer', models.JSONField(default=dict)),
                ('hash', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'cellar3_datasets',
            },
        ),
    ]
