# Generated by Django 4.2.4 on 2024-09-06 17:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cellar3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('submission_date', models.DateTimeField()),
                ('maintainer_email', models.EmailField(max_length=500)),
                ('maintainer_name', models.CharField(max_length=500)),
                ('decision_date', models.DateTimeField()),
                ('status', models.CharField(
                    choices=[('received', 'Received'), ('accepted', 'Accepted'), ('rejected', 'Rejected')],
                    default='received', max_length=20)),
                ('conversion_status', models.CharField(
                    choices=[('sent', 'Sent'), ('received', 'Received'), ('running', 'Running'), ('success', 'Success'),
                             ('error', 'Error')], max_length=20)),
                ('error', models.CharField(blank=True, max_length=5000, null=True)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('rds_path', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='')),
                ('h5ad_path', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='')),
            ],
            options={
                'db_table': 'cellar3_submissions',
            },
        ),
    ]
