# Generated by Django 4.2.4 on 2024-09-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cellar3', '0002_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='conversion_status',
            field=models.CharField(
                choices=[('initial', 'Initial'), ('sent', 'Job Submitted'), ('received', 'Job Received'),
                         ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='initial',
                max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='decision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
