# Generated by Django 4.2.4 on 2024-09-13 15:55

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cellar3', '0003_alter_submission_conversion_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasetmeta',
            options={'verbose_name': 'Dataset', 'verbose_name_plural': 'Datasets'},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='h5ad_path',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='rds_path',
        ),
        migrations.AddField(
            model_name='submission',
            name='h5ad',
            field=models.FileField(null=True,
                                   storage=django.core.files.storage.FileSystemStorage(location='data\\submissions'),
                                   upload_to=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='rds',
            field=models.FileField(null=True,
                                   storage=django.core.files.storage.FileSystemStorage(location='data\\submissions'),
                                   upload_to=''),
        ),
    ]
